# Generated by Django 5.2.13 on 2026-04-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapperCareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('skill_matches', models.JSONField(default=list)),
                ('interest_matches', models.JSONField(default=list)),
                ('best_for', models.JSONField(default=list)),
                ('roadmap', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Career path',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MapperInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mapper interest',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MapperSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_base', models.BooleanField(default=True, help_text='If true, the skill appears in the default skill chip list.')),
            ],
            options={
                'verbose_name': 'Mapper skill',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
