# Generated by Django 5.2.13 on 2026-04-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParallelDomainInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('analysis', models.TextField()),
                ('salary_text', models.CharField(max_length=64)),
                ('salary_min', models.PositiveIntegerField()),
                ('salary_max', models.PositiveIntegerField()),
                ('growth', models.CharField(max_length=255)),
                ('growth_score', models.PositiveIntegerField()),
                ('demand', models.TextField()),
                ('demand_score', models.PositiveIntegerField()),
                ('skills', models.JSONField(default=list)),
                ('recommendation', models.TextField()),
                ('why_recommended', models.JSONField(default=list)),
                ('choose_if_primary', models.JSONField(default=list)),
                ('choose_if_other', models.JSONField(default=list)),
                ('final_suggestion', models.TextField()),
            ],
            options={
                'verbose_name': 'Parallel domain insight',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
