# Generated by Django 5.2.13 on 2026-04-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parallel_insights', '0002_seed_parallel_insights_defaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paralleldomaininsight',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Parallel Career Insights domain', 'verbose_name_plural': 'Parallel Career Insights domains'},
        ),
        migrations.AlterField(
            model_name='paralleldomaininsight',
            name='color',
            field=models.CharField(help_text='Hex color for UI accents, e.g. #FF6B6B', max_length=32),
        ),
        migrations.AlterField(
            model_name='paralleldomaininsight',
            name='name',
            field=models.CharField(help_text='Shown in the Parallel Career Insights dropdowns and comparison cards.', max_length=255, verbose_name='Domain name'),
        ),
        migrations.AlterField(
            model_name='paralleldomaininsight',
            name='slug',
            field=models.SlugField(help_text='Stable id used in the API and URL (e.g. ai, ml, web). Do not change lightly.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='paralleldomaininsight',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in the domain lists (lower = first).'),
        ),
    ]
