"""Default Parallel Career Insights rows (mirrors former parallelInsights.tsx)."""

SEED_DOMAINS = [
	{
		"slug": "ai",
		"name": "Artificial Intelligence",
		"color": "#FF6B6B",
		"sort_order": 0,
		"description": "Focus on intelligent systems, automation, NLP, robotics, and advanced problem-solving",
		"analysis": "Broad field requiring strong fundamentals in algorithms, mathematics, and programming",
		"salary_text": "₹10–25 LPA",
		"salary_min": 10,
		"salary_max": 25,
		"growth": "Extremely High 🚀",
		"growth_score": 95,
		"demand": "Rapidly increasing with high competition",
		"demand_score": 90,
		"skills": ["Python", "Deep Learning", "NLP", "Computer Vision", "Neural Networks", "TensorFlow/PyTorch"],
		"recommendation": "AI is better suited if you are interested in innovation, broad applications, and cutting-edge technology.",
		"why_recommended": [
			"Matches your skills in Python & problem solving",
			"Aligns with your interest in innovation and advanced technologies",
			"Higher long-term growth potential",
			"Strong market demand with premium salaries",
		],
		"choose_if_primary": [
			"You enjoy innovation, research, and building intelligent systems",
			"You want high growth and future opportunities",
			"You are comfortable with complex concepts (Deep Learning, NLP)",
			"You aim for cutting-edge technology roles",
		],
		"choose_if_other": [
			"You prefer data analysis and predictive modeling",
			"You like working with algorithms and structured data",
			"You want a focused and practical career path",
		],
		"final_suggestion": "Based on your current profile, AI is the best career path for you. With strong fundamentals and passion for innovation, you can excel in this field.",
	},
	{
		"slug": "ml",
		"name": "Machine Learning",
		"color": "#4ECDC4",
		"sort_order": 1,
		"description": "Focus on data-driven models, predictive systems, and algorithm optimization",
		"analysis": "Specialized subset with more focused approach on algorithms and statistical methods",
		"salary_text": "₹8–20 LPA",
		"salary_min": 8,
		"salary_max": 20,
		"growth": "Very High 📊",
		"growth_score": 85,
		"demand": "High and stable across industries",
		"demand_score": 85,
		"skills": ["Python", "Statistics", "Algorithms", "Data Analysis", "Scikit-learn", "Pandas"],
		"recommendation": "ML is better if you prefer focused data-driven modeling with clear, measurable outcomes.",
		"why_recommended": [
			"Strong alignment with data analysis interests",
			"Practical and focused career path",
			"High demand across industries",
			"Clear progression and measurable outcomes",
		],
		"choose_if_primary": [
			"You prefer data analysis and predictive modeling",
			"You like working with algorithms and structured data",
			"You want a focused and practical career path",
			"You value measurable and concrete results",
		],
		"choose_if_other": [
			"You enjoy innovation and research",
			"You want to work on broad intelligent systems",
			"You are interested in cutting-edge technologies",
		],
		"final_suggestion": "Machine Learning offers a balanced path combining innovation with practical application. Ideal for those who want to see immediate impact of their work.",
	},
	{
		"slug": "ds",
		"name": "Data Science",
		"color": "#45B7D1",
		"sort_order": 2,
		"description": "Transform raw data into actionable insights using analytics and visualization",
		"analysis": "Blend of statistics, programming, and domain knowledge for business intelligence",
		"salary_text": "₹9–22 LPA",
		"salary_min": 9,
		"salary_max": 22,
		"growth": "Very High 📈",
		"growth_score": 88,
		"demand": "Consistently high across all sectors",
		"demand_score": 87,
		"skills": ["Python", "SQL", "Statistics", "Tableau/PowerBI", "Excel", "A/B Testing"],
		"recommendation": "Data Science is ideal if you enjoy working with large datasets and deriving business insights.",
		"why_recommended": [
			"Excellent for analytical minds",
			"High demand across all industries",
			"Direct impact on business decisions",
			"Growing opportunities in AI/ML integration",
		],
		"choose_if_primary": [
			"You enjoy working with large datasets",
			"You want to derive business insights from data",
			"You prefer analytical and visualization work",
			"You enjoy storytelling with data",
		],
		"choose_if_other": [
			"You want to build intelligent systems",
			"You prefer development over analysis",
			"You're interested in cutting-edge research",
		],
		"final_suggestion": "Data Science is perfect if you want to influence business strategy through analysis. Combines analytical rigor with business impact and creativity.",
	},
	{
		"slug": "web",
		"name": "Web Development",
		"color": "#96CEB4",
		"sort_order": 3,
		"description": "Build user-facing applications and interfaces for web platforms",
		"analysis": "Fast-paced field focused on UI/UX, responsive design, and client-side technologies",
		"salary_text": "₹5–18 LPA",
		"salary_min": 5,
		"salary_max": 18,
		"growth": "High and Stable 📱",
		"growth_score": 75,
		"demand": "Consistent demand with evolving standards",
		"demand_score": 80,
		"skills": ["JavaScript/TypeScript", "React/Vue", "HTML/CSS", "Node.js", "Git", "Responsive Design"],
		"recommendation": "Web Development suits you if you enjoy creating user experiences and seeing immediate results.",
		"why_recommended": [
			"High demand and consistent opportunities",
			"Immediate visual feedback on your work",
			"Fast-paced learning environment",
			"Strong community and resources",
		],
		"choose_if_primary": [
			"You enjoy creating user experiences",
			"You want to see immediate results",
			"You prefer visual and creative work",
			"You enjoy collaborative development",
		],
		"choose_if_other": [
			"You prefer backend systems and logic",
			"You want to work on intelligent systems",
			"You are interested in data analysis",
		],
		"final_suggestion": "Web Development is ideal if you love creating interactive experiences. Perfect entry point into tech with continuous learning opportunities.",
	},
	{
		"slug": "fullstack",
		"name": "Full Stack Development",
		"color": "#FFEAA7",
		"sort_order": 4,
		"description": "Master both frontend and backend technologies for complete application development",
		"analysis": "Comprehensive approach requiring expertise across multiple layers of technology stack",
		"salary_text": "₹7–22 LPA",
		"salary_min": 7,
		"salary_max": 22,
		"growth": "Very High 🚀",
		"growth_score": 86,
		"demand": "Extremely high across startups and enterprises",
		"demand_score": 92,
		"skills": ["JavaScript/TypeScript", "React", "Node.js", "Databases", "APIs", "DevOps Basics"],
		"recommendation": "Full Stack is perfect if you want versatility and the ability to own projects end-to-end.",
		"why_recommended": [
			"Extremely high market demand",
			"Full ownership of product features",
			"Better salary prospects",
			"Versatile across industries",
		],
		"choose_if_primary": [
			"You want complete control over projects",
			"You prefer end-to-end development",
			"You enjoy learning diverse technologies",
			"You aspire to leadership roles",
		],
		"choose_if_other": [
			"You prefer specialization over generalization",
			"You want to focus on specific areas",
			"You prefer deeper expertise in one area",
		],
		"final_suggestion": "Full Stack Development offers maximum flexibility and growth. Best for ambitious developers who want to own entire features and lead projects.",
	},
	{
		"slug": "cybersec",
		"name": "Cyber Security",
		"color": "#DDA0DD",
		"sort_order": 5,
		"description": "Protect systems, networks, and data from security threats and vulnerabilities",
		"analysis": "Specialized field with growing importance in digital transformation and compliance",
		"salary_text": "₹8–24 LPA",
		"salary_min": 8,
		"salary_max": 24,
		"growth": "Extremely High 🔒",
		"growth_score": 93,
		"demand": "Rapidly increasing with critical need",
		"demand_score": 91,
		"skills": ["Network Security", "Ethical Hacking", "Linux/Windows", "Python", "Cryptography", "Security Tools"],
		"recommendation": "Cyber Security is ideal if you're passionate about protecting systems and preventing attacks.",
		"why_recommended": [
			"Critical and growing field globally",
			"Highest growth trajectory in tech",
			"Well-compensated roles",
			"Meaningful work protecting systems",
		],
		"choose_if_primary": [
			"You're passionate about protecting systems",
			"You enjoy problem-solving and investigation",
			"You want to work in a critical field",
			"You prefer security and compliance focus",
		],
		"choose_if_other": [
			"You prefer development and building",
			"You want user-facing work",
			"You prefer data analysis",
		],
		"final_suggestion": "Cyber Security is ideal for those passionate about protection and defense. Offers critical role in digital transformation with premium compensation.",
	},
]
